### ISSUE TITLE
Write unit test for the ViewModel

### ISSUE THREAD

**Issue by mertceyhan** [mertceyhan/bitcoin-market-android#13]

**Comment by Kardelio** [comment]
My dude! How would you feel about me giving this a spin?

**Comment by mertceyhan** [comment]
Hey mate! Of course, it will help a lot. The issue is yours, thanks in advance  🙏  Just, I've looked at the way of testing multiple values of [State](https://developer.android.com/reference/kotlin/androidx/compose/runtime/State) and I think [snapshotFlow](https://developer.android.com/reference/kotlin/androidx/compose/runtime/package-summary#snapshotFlow(kotlin.Function0)) can help us but I'm open to your idea too. You know the job 🙌

**Comment by Kardelio** [comment]
Ty dude! Ill get to it ASAP

**Comment by Kardelio** [comment]
Awesome! TY <3 is there any Compose stuff I can help with on this app? Got a hankering for some juicy composeeeee?
