### ISSUE TITLE
Create a widget 

### ISSUE THREAD

**Issue by mertceyhan** [mertceyhan/bitcoin-market-android#18]
https://developer.android.com/guide/topics/appwidgets/overview

**Comment by enofeb** [comment]
If there is no assignee , could you assign to me?

**Comment by mertceyhan** [comment]
Hey @enofeb! Of course, you can take the task. Do you have an idea for the widget design?

**Comment by enofeb** [comment]
Actually I don't for now. It is my starting point. If you have any idea, you can share with me. If I found something , I will share here as well.

**Comment by mertceyhan** [comment]
I've tried to apply Coinbase design to the app, we can follow the same thing for the widget. Coinbase's Android app has good widgets.

**Comment by mertceyhan** [comment]
What do you think?

![Screenshot_20211216-122117](https://user-images.githubusercontent.com/22434597/146343938-150c90e6-1152-457e-992c-345d4b76c04c.png)

**Comment by enofeb** [comment]
Thats cool! I had a look binance widget. It is almost same structure. We can go like coinbase design if there is no functionality restrictions.
![Screenshot_20211216-122740.jpg](https://user-images.githubusercontent.com/26115983/146344819-99323410-d4aa-4bff-8e0c-5fec6442ee3e.jpg)

**Comment by mertceyhan** [comment]
I agree, they're almost the same, it's up to you.  Please let me know if there is anything I can help. Thanks in advance 🙏

**Comment by enofeb** [comment]
Got it! My pleasure👋

**Comment by enofeb** [comment]
Hello @mertceyhan 
You know that we have refresh button in design. We need to fetch updated price and show in widget. My question is ;  if we send a request each time when refresh button is pressed , it can be expensive? What do you think?

**Comment by mertceyhan** [comment]
Hi @enofeb! Thank you for sharing your concern and you're absolutely right. @barissaglam is working on a caching mechanism (https://github.com/mertceyhan/bitcoin-market-android/issues/25). My recommendation is to wait for this improvement and after that implement the widget.

**Comment by mertceyhan** [comment]
Hey @enofeb! Could you open a PR one more time, please? It's my bad, I forgot to squash commits. 🤦‍♂️

**Comment by enofeb** [comment]
I've opened bro

**Comment by mertceyhan** [comment]
Thanks a lot, it looks perfect. Good job 👏  👏  👏

**Comment by enofeb** [comment]
Thank you for your attention too bro🙏🏻
