### ISSUE TITLE
Double Splash Screen

### ISSUE THREAD

**Issue by JamalMulla** [mertceyhan/bitcoin-market-android#34]
First the default splash screen (https://developer.android.com/guide/topics/ui/splash-screen) plays and then the additional one implemented in the app. Is this intentional? It seems a bit weird. I think it would be an improvement if the default one was disabled.

**Comment by mertceyhan** [comment]
Hey @JamalMulla, it's a good point. The current Splash screen is a regular screen and it does not have an advance. If you want you can implement [SplashScreen API](https://developer.android.com/guide/topics/ui/splash-screen) for Android 12 and above.

**Comment by mertceyhan** [comment]
You know, A lot of application has a splash screen, just I wanted to create it by default and show the application icon. Also, I wanted to show navigation between two screens. Splash to Main is a great example of this.
