### ISSUE TITLE
Need to Be Upgrade Room version to 2.4.2

### ISSUE THREAD

**Issue by admcilgin** [mertceyhan/bitcoin-market-android#46]
RoomDb version should be upgraded. With current version "2.3.0" it can not compile on M1 MacBooks 
following exception occurred on m1 Macs ```Caused by: java.lang.Exception: No native library is found for os.name=Mac and     os.arch=aarch64.``` 

current room version : 2.3.0 
expected room version: 2.4.2

**Comment by mertceyhan** [comment]
Hi @admcilgin, thanks for the ticket! I've updated the dependency versions to their latest.
