### ISSUE TITLE
Chart prices don't seem on the dark theme.

### ISSUE THREAD

**Issue by mertceyhan** [mertceyhan/bitcoin-market-android#5]
A small bug came with dark theme support. Currently, chart prices don't seem on the dark theme.

![Screenshot_1616435672](https://user-images.githubusercontent.com/22434597/112035794-f3de2a80-8b50-11eb-9599-88b0390711e5.png)

**Comment by mertceyhan** [comment]
@masreplay want to fix?

**Comment by masreplay** [comment]
@mertceyhan yes yes of course, I missed it😁

**Comment by mertceyhan** [comment]
Fixed ✅
