### ISSUE TITLE
show list of crypto

### ISSUE THREAD

**Issue by abdalla19977** [mertceyhan/bitcoin-market-android#6]
I think it will be a good idea to add recyclerview inside a fragment to show multiple currencies, in this case we will cover multiple android topics, we can also cache them with room

**Comment by AhmedWayes** [comment]
don't think again @abdalla19977

**Comment by mertceyhan** [comment]
That is a showcase to implementing popular library and Google suggested architecture. I don't think to add a new feature, please just open an issue to improve the current implementation.
